/**
 * Demo Report Card Data - Matches exact API response structure
 * For UI testing/visualization before actual API integration
 */

import type { ReportCardResult } from "@/types/reportCard";

export const DEMO_REPORT_CARD_DATA: ReportCardResult = {
  meta_statistics: {
    quizzes_accuracy_percent: 87.5,
    xp_total_tokens: 1250,
    total_study_time: 1847, // minutes (~30.8 hours)
    total_modules_completed: 6,
    total_completed_certificates: 4,
    user_avatar_level: 5,
    user_risk_level: "Low",
    global_progress_percentage: 78,
    leaderboard_rank: 8,
  },
  campaigns: [
    {
      campaign_name: "Q1 2026 Security Awareness",
      completed_modules: [
        {
          module_id: 1,
          module_name: "Phishing Awareness Fundamentals",
          status: "completed",
          maximum_xp_tokens: 230,
          achieved_xp_tokens: 210,
          maximum_compliance_score: 300,
          achieved_compliance_score: 285,
          total_attempted_quizzes: 3,
          total_correct_answers: 9,
          achievements_unlocked_in_module: 2,
          certificate_issued: "Yes",
          module_completion_date: "15-Jan-2026",
          quiz_percentage: 90,
          duration_minutes: 45,
        },
        {
          module_id: 2,
          module_name: "Password Security Best Practices",
          status: "completed",
          maximum_xp_tokens: 230,
          achieved_xp_tokens: 195,
          maximum_compliance_score: 300,
          achieved_compliance_score: 265,
          total_attempted_quizzes: 2,
          total_correct_answers: 8,
          achievements_unlocked_in_module: 1,
          certificate_issued: "Yes",
          module_completion_date: "22-Jan-2026",
          quiz_percentage: 85,
          duration_minutes: 60,
        },
        {
          module_id: 3,
          module_name: "Data Protection & Privacy",
          status: "completed",
          maximum_xp_tokens: 230,
          achieved_xp_tokens: 218,
          maximum_compliance_score: 300,
          achieved_compliance_score: 290,
          total_attempted_quizzes: 3,
          total_correct_answers: 10,
          achievements_unlocked_in_module: 3,
          certificate_issued: "Yes",
          module_completion_date: "05-Feb-2026",
          quiz_percentage: 95,
          duration_minutes: 60,
        },
      ],
    },
    {
      campaign_name: "Advanced Threat Detection",
      completed_modules: [
        {
          module_id: 4,
          module_name: "Malware Recognition & Prevention",
          status: "completed",
          maximum_xp_tokens: 230,
          achieved_xp_tokens: 205,
          maximum_compliance_score: 300,
          achieved_compliance_score: 275,
          total_attempted_quizzes: 2,
          total_correct_answers: 8,
          achievements_unlocked_in_module: 2,
          certificate_issued: "Yes",
          module_completion_date: "12-Feb-2026",
          quiz_percentage: 88,
          duration_minutes: 60,
        },
        {
          module_id: 5,
          module_name: "Social Engineering Tactics",
          status: "completed",
          maximum_xp_tokens: 230,
          achieved_xp_tokens: 212,
          maximum_compliance_score: 300,
          achieved_compliance_score: 288,
          total_attempted_quizzes: 3,
          total_correct_answers: 9,
          achievements_unlocked_in_module: 2,
          certificate_issued: "Yes",
          module_completion_date: "24-Feb-2026",
          quiz_percentage: 92,
          duration_minutes: 60,
        },
        {
          module_id: 6,
          module_name: "Incident Response Procedures",
          status: "completed",
          maximum_xp_tokens: 230,
          achieved_xp_tokens: 210,
          maximum_compliance_score: 300,
          achieved_compliance_score: 280,
          total_attempted_quizzes: 2,
          total_correct_answers: 7,
          achievements_unlocked_in_module: 1,
          certificate_issued: "Not yet",
          module_completion_date: "28-Feb-2026",
          quiz_percentage: 80,
          duration_minutes: 30,
        },
      ],
    },
  ],
};
